[package]
name = "bevy_tilemap_base"
version = "0.1.0"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["dim2"]

# 2D
dim2 = []
dim2-enhanced-determinism = ["bevy_rapier2d/enhanced-determinism"]
dim2-parallel = ["bevy_rapier2d/parallel"]
dim2-serde-serialize = ["bevy_rapier2d/serde-serialize"]
dim2-simd-nightly = ["bevy_rapier2d/simd-nightly"]
dim2-simd-stable = ["bevy_rapier2d/simd-stable"]
dim2-wasm-bindgen = ["bevy_rapier2d/wasm-bindgen"]

# 3D
dim3 = []
dim3-enhanced-determinism = ["bevy_rapier3d/enhanced-determinism"]
dim3-parallel = ["bevy_rapier3d/parallel"]
dim3-serde-serialize = ["bevy_rapier3d/serde-serialize"]
dim3-simd-nightly = ["bevy_rapier3d/simd-nightly"]
dim3-simd-stable = ["bevy_rapier3d/simd-stable"]
dim3-wasm-bindgen = ["bevy_rapier3d/wasm-bindgen"]

[dependencies]
bevy_app = "0.4"
bevy_asset = "0.4"
bevy_core = "0.4"
bevy_ecs = "0.4"
bevy_log = "0.4"
bevy_math = "0.4"
bevy_rapier2d = { version = "0.7.0", optional = true }
bevy_rapier3d = { version = "0.7.0", optional = true }
bevy_render = "0.4"
bevy_reflect = "0.4"
bevy_sprite = "0.4"
bevy_tilemap_core = { path = "../core", version = "0.4" }
bevy_tilemap_types = { path = "../types", version = "0.4" }
bevy_transform = "0.4"
bevy_utils = "0.4"
bevy_window = "0.4"
bitflags = "1.2"
hexasphere = "3.1"
serde = { version = "1.0", features = ["derive"], optional = true }
